function [] = remove(  )
[DataIn1,Fs]=audioread('noisadd.wav');
%read an audio file returning the sampled data into DataIn and the sample
%rate into fs ,in Hertz.[DataIn,Fs] are now output arguments.
DataOut1 = filter(LowPass4k,DataIn1);
% applies a bandstop filter to the audio file
sound(DataOut1,Fs);
%play the filtered audio file
audiowrite('anotherfilename.wav',DataOut1,Fs);% write the newly filtered audio file as a new file
% the following functions are the filters used to filter the audio file.
function Hd = LowPass4k
%LOWPASS4K Returns a discrete-time filter object.
% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 20-Dec-2022 21:56:46
% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.
% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency
N  = 100;   % Order
Fc = 4000;  % Cutoff Frequency
% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');
end
% [EOF]

end

